name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy files to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ~/private_key.pem # Save to home directory
          chmod 600 ~/private_key.pem
          scp -o StrictHostKeyChecking=no -i ~/private_key.pem -r ./* $USER@$HOST:/var/www/html/
          rm ~/private_key.pem # Clean up the key file after use
          
      - name: Restart Nginx
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/private_key.pem $USER@$HOST "sudo systemctl restart nginx"
